M48
; DRILL file {KiCad 9.0.1} date 2025-04-11T19:14:00-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-11T19:14:00-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C12.100
%
G90
G05
T1
X99.8Y-143.75
X99.85Y-65.2
X164.95Y-143.8
X165.0Y-65.25
T2
X115.6Y-118.65
X152.2Y-118.6
M30
